---
all:
  children:
    k8s_cluster:
      children:
        k8s_masters:
          hosts:
            server1:
              ansible_user: khoupeurt
              ansible_host: 164.92.232.110
              ansible_ssh_private_key_file: ~/.ssh/firestudio
